// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVirkKTdYVnUWgWSi1qqtLHPEZyyVJ_0o',
    appId: '1:1035718047234:web:f866594d14ef27d875591b',
    messagingSenderId: '1035718047234',
    projectId: 'mcemeurccart',
    authDomain: 'mcemeurccart.firebaseapp.com',
    storageBucket: 'mcemeurccart.appspot.com',
    measurementId: 'G-WEH1VS69B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyD2hSTOquuFA4Ks-46oAplmpz8hObl_U',
    appId: '1:1035718047234:android:a341bb3488eab3ee75591b',
    messagingSenderId: '1035718047234',
    projectId: 'mcemeurccart',
    storageBucket: 'mcemeurccart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDME2taNkhiNUWLaD7ZbnFXG2ZRDNWuQMk',
    appId: '1:1035718047234:ios:fbff882eda51316375591b',
    messagingSenderId: '1035718047234',
    projectId: 'mcemeurccart',
    storageBucket: 'mcemeurccart.appspot.com',
    iosClientId: '1035718047234-b3iv4i5pa7asej2c05mvsoarbmkogr21.apps.googleusercontent.com',
    iosBundleId: 'com.example.mcemeurckart',
  );
}
